Todo list initial
AbuTalha3/Todo-list pull request #2
Opened 2023-07-13 19:14 UTC by AbuTalha3

In this PR I have;-
-Worked on (Adding a new item to the TODO list.)
-Added (Removing button for a selected item randomly.)
-Completed the (Marking a selected item as complete.)
-Added Button at the bottom for (Removing all items marked as complete at once.)

2023-07-13 20:57 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @AbuTalha3, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that has no README file. Kindly follow [Microverse Template](https://github.com/microverseinc/readme-template) to make your professional README.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-13 21:45 UTC, Ibizugbe approved these changes
Hi @AbuTalha3 👋👋👋, 

![approve2](https://github.com/AbuTalha3/Todo-list/assets/64643995/7340ac6b-1bd2-4d2f-8e0e-b6d27eb8a7d6)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] It has one new `.js` file imported as a module👍.
- [x] It has event listener on checkbox change👍.
- [x] Data is persisted to local storage👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 05:00 UTC, Efiamotu-1 requested changes
Hi @AbuTalha3 , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 05:00 UTC, Efiamotu-1 commented on README.md
- [x] Your usage section of your readme is not correctly written to enable user run the application locally please kindly see the example below and make the necessary changes. 👍 ✨ 
-  example
- > After installing the project, run the following command:
- run `npm run start` or `npm start` to open the project in your browser 
- * This is all that should be required of you to assist anyone using your app for the first time whether it is a developer or just a random user 👍

2023-07-14 05:00 UTC, Efiamotu-1 commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [x] Your mit license link is broken as shown in the image below once clicked it shows a 404 error. please kindly ensure you fix this 👍 ✨ 
- [ ] Also the link to your issues as well is broken please kindly provide the appropriate link to it so that your readme looks professional 👍 ✨ 
![bm](https://github.com/AbuTalha3/Todo-list/assets/89055502/da09ce90-14f1-4433-b1ba-4ca5b279c9d7)

2023-07-14 05:00 UTC, Efiamotu-1 commented on src/index.html
- [ ] YOur design currently does not match closely the provided project design as shown below. Please kindly make sure to correct some spacing and overall alignments of the contents of the todolist as shown below. 👍 
- project design
![pd](https://github.com/AbuTalha3/Todo-list/assets/89055502/c7ae69e9-5158-4d16-b5fa-62329cd209a1)
- your design
![yd](https://github.com/AbuTalha3/Todo-list/assets/89055502/97dcb7ab-6915-4539-a3ec-d6da7ade8d76)

2023-07-14 12:28 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @AbuTalha3, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Fair README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 12:28 UTC, Qoosim commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] Kindly attend to the issue link. It is yet to be fixed.

### Issue Page
![issue](https://github.com/AbuTalha3/Todo-list/assets/26597432/d90f60c5-bd6c-42fa-a2fb-d04ff3b7f15c)

2023-07-14 12:28 UTC, Qoosim commented on src/index.js
> +
- [ ] Great job implementing the required changes from the previous reviewer. I guessed you tampered something while trying to make some changes suggested to you. At this moment, at the page load, your todo list items do not render to the page. Kindly look into it and fix.

#### Your App
![your-app](https://github.com/AbuTalha3/Todo-list/assets/26597432/f6c1ec4c-b3f2-421c-acc7-9ec83a349d37)

### Template
![temp-app](https://github.com/AbuTalha3/Todo-list/assets/26597432/d911ffff-94ba-475f-8487-d4da8e115748)

2023-07-14 14:40 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @AbuTalha3, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application works as expected :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:  
- [x] Implemented changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 14:44 UTC, merged