Updated required changes
AbuTalha3/Todo-list pull request #3
Opened 2023-07-14 16:55 UTC by AbuTalha3

In this PR the requirements were;-
- Adding a new item function to work.
- Removing a selected item to function.
- Marking a selected item as complete.
 -Removing all items marked as complete at once.
- Added features of the Project to README file.

2023-07-14 17:54 UTC, Ibizugbe requested changes
Hi @AbuTalha3 👋👋👋, 

![tryagain](https://github.com/AbuTalha3/Todo-list/assets/64643995/ad309297-82f0-430b-9617-6b95c7da650d)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] A function for adding a new task has been implemented👍.
- [x] A function for editing a task has been implemented👍.
- [x] A function for deleting a task has been implemented👍.
- [x] A function to clear completed tasks has been implemented👍.
- [x] Linters are passing👍.


## Required Changes ♻️

- [ ] Nice job so far👍. but just as required for this milestone, kindly remove all hardcoded items from the task array and create a new js file and add all the new functionalities in it😉.
<img width="674" alt="image" src="https://github.com/AbuTalha3/Todo-list/assets/64643995/066f0c46-b8f2-4c39-92bc-5d15163255cf">

<img width="430" alt="image" src="https://github.com/AbuTalha3/Todo-list/assets/64643995/ee8b5a9f-68f9-47dd-8608-02fc2102b737">

- [ ] Your changes are currenly not stored in localstorage and it is a requirement in this milestone that all changes should be saved in localstorage😉. Kindly do well to make the necessary adjustments👍. When the changes are made, your page should be able to retain it's content when the page is loaded since it renders the data stored in the local storage😉.
<img width="395" alt="image" src="https://github.com/AbuTalha3/Todo-list/assets/64643995/b07e6590-4273-493e-a491-eae0dbb54598">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 23:55 UTC, rotimiazeez requested changes
Hi @AbuTalha3 😉, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlight 
* Good job saving all changes to the To-Do List in local storage. 👍🏽

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-07-14 23:55 UTC, rotimiazeez commented on src/todos.js
> +  });
Please note that deleting a task should update all remaining items' indexes, so they represent the current list order and are unique (i.e. if a task is removed, then added back to the list, the index of that task should equal the total number of tasks
![Screenshot from 2023-07-15 00-49-27](https://github.com/AbuTalha3/Todo-list/assets/44624138/07e3c8ac-f9cf-4671-8086-6b4a7198b4e8)
).

2023-07-14 23:55 UTC, rotimiazeez commented on src/todos.js
> +  });
As stated by the previous CR, kindly remove the hardcoded item from your index.js.

2023-07-15 07:57 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ 🎉 ✔️ 

Hi @AbuTalha3, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] Implemented all requested changes ✔️ 
- [ ] Correct GitHub flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 07:57 UTC, cynthiainga commented on src/todos.js
> +  }
- [Optional] I noticed that when I click on the refresh button it removes all the items from the list, the refresh button is supposed to refresh the page and not delete the items. Please kindly fix that 🙏🏾

2023-07-15 07:57 UTC, cynthiainga commented on src/todos.js
> +/* eslint-disable no-use-before-define */
- [Optional] It's not a good approach to disable linters, fixing linters help us to write a clean, clear, and good codebase, kindly make sure to not disable linters 🙏🏾

2023-07-15 08:00 UTC, merged